### ISSUE TITLE
Manual - How to program STM8

### ISSUE THREAD

**Issue by vslinuxdotnet** [baruch/b3603#19]
Hello,
Can you provide some how to about the "byte options" to flash the the *.ihx hex?
I flash the STM8 with ST-LINK with ST Visual Programmer, but in the display only shows random digit from 6 to 8 in B3603 module.
I also try with your old *.ihx hex file with same results.
Please point me in the right path.
Thank you.

**Comment by baruch** [comment]
The display screen is not supported in my firmware version, unfortunately. Only the serial was ever made to work. I know there is some work to make it work by others.
